
[target.thumbv7m-none-eabi]
runner = 'arm-none-eabi-gdb'
# runner = 'probe-run --chip STM32F103C8'
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
[profile.dev]
opt-level = "z"

[build]
target = "thumbv7m-none-eabi"